services:
  - type: web
    name: laravel-blade-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:your-app-key==  # Generate with php artisan key:generate --show
      - key: APP_URL
        value: https://your-render-url.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-clevercloud-mysql-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your-db-name
      - key: DB_USERNAME
        value: your-db-user
      - key: DB_PASSWORD
        value: your-db-password
